name: flutter_coffee_shop_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.3.1
  device_preview_screenshot: ^1.0.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  smooth_page_indicator: ^1.1.0
  stylish_bottom_bar: ^1.0.1
  supabase_flutter: ^2.10.1
  barcode_widget: ^2.0.1
  google_mlkit_barcode_scanning: ^0.3.0
  mobile_scanner: ^7.1.2
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.3
  uni_links: ^0.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
